In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\ARSHAD MALIK\system\Global_Superstore_Data.csv")

In [2]:
# import os

In [3]:
# os.chdir(r"C:\Users\ARSHAD MALIK\Music\Downloads")

In [4]:
# os.listdir(r"C:\Users\ARSHAD MALIK\Music\Downloads")

In [5]:
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,11-11-2014,11/13/2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,$221.98,2,0.0,$62.15,40.77,High
1,26341,IN-2014-JR162107-41675,02-05-2014,02-07-2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,($288.77),923.63,Critical

In [6]:
df.shape

(51290, 24)

In [7]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Postal Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [8]:
dff=df['Shipping Cost']>500

In [9]:
dff.value_counts()

False    51170
True       120
Name: Shipping Cost, dtype: int64

In [10]:
df[dff]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
1,26341,IN-2014-JR162107-41675,02-05-2014,02-07-2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,($288.77),923.63,Critical
2,25330,IN-2014-CR127307-41929,10/17/2014,10/18/2014,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,$919.97,915.49,Medium
3,13524,ES-2014-KM1637548-41667,1/28/2014,1/30/2014,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless","$2,892.51",5,0.1,($96.54),910.16,Medium
4,47221,SG-2014-RH9495111-41948,11-05-2014,11-06-2014,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed","$2,832.96",8,0.0,$311.52,903.04,Critical
5,22732,IN-2014-JM156557-41818,6/28/2014,07-01-2014,Second Class,JM-156557,Jim Mitchum,Corporate,NaN,Sydney,...,TEC-PH-5842,Technology,Phones,"Samsung Smart Phone, with Caller ID","$2,862.68",5,0.1,$763.28,897.35,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46629,39399,CA-2013-SB20185140-41416,5/22/2013,5/26/2013,Standard Class,SB-201851404,Sarah Brown,Consumer,90045.0,Los Angeles,...,TEC-MA-6631,Technology,Machines,Zebra GX420t Direct Thermal/Thermal Transfer P...,"$2,973.32",7,0.2,$334.50,510.18,High
48570,46366,CA-2015-SV1081523-42361,12/23/2015,12/25/2015,Second Class,SV-1081523,Stuart Van,Corporate,NaN,Montrï¿½al,...,TEC-PH-5268,Technology,Phones,"Motorola Smart Phone, Full Size","$3,863.88",6,0.0,"$1,159.02",546.56,Critical
48607,31784,CA-2012-SA20830140-41210,10/28/2012,10/30/2012,First Class,SA-208301402,Sue Ann Reed,Consumer,60610.0,Chicago,...,TEC-PH-3138,Technology,Phones,Apple iPhone 5S,"$2,735.95",6,0.2,$341.99,752.51,High
49493,36178,CA-2015-TB21175140-42311,11-03-2015,11-06-2015,Second Class,TB-211751408,Thomas Boland,Corporate,42420.0,Henderson,...,TEC-AC-5098,Technology,Accessories,Logitech diNovo Edge Keyboard,"$2,249.91",9,0.0,$517.48,780.70,Critical
50010,38540,CA-2015-TP21415140-42234,8/18/2015,8/23/2015,Second Class,TP-214151406,Tom Prescott,Consumer,19134.0,Philadelphia,...,FUR-CH-4623,Furniture,Chairs,HON 5400 Series Task Chairs for Big and Tall,"$4,416.17",9,0.3,($630.88),566.65,Medium

In [11]:
pd.isnull(df["Segment"])

0        False
1        False
2        False
3        False
4        False
         ...
51285    False
51286    False
51287    False
51288    False
51289    False
Name: Segment, Length: 51290, dtype: bool

In [12]:
pd.isnull(df["Segment"]).sum()

0

In [13]:
pd.notnull(df["Segment"]).sum()

51290

In [14]:
pd.isnull(df["Country"]).sum()

0

In [15]:
pd.notnull(df["Country"]).sum()

51290

In [16]:
pd.isnull(df["Region"]).sum()

0

In [17]:
pd.notnull(df["Region"]).sum()

51290

In [18]:
pd.notnull(df["Sub-Category"]).sum()

51290

In [19]:
pd.notnull(df["Category"]).sum()

51290

In [20]:
pd.notnull(df["Market"]).sum()

51290

In [21]:
df[dff].head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
1,26341,IN-2014-JR162107-41675,02-05-2014,02-07-2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,($288.77),923.63,Critical
2,25330,IN-2014-CR127307-41929,10/17/2014,10/18/2014,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,$919.97,915.49,Medium
3,13524,ES-2014-KM1637548-41667,1/28/2014,1/30/2014,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless","$2,892.51",5,0.1,($96.54),910.16,Medium
4,47221,SG-2014-RH9495111-41948,11-05-2014,11-06-2014,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed","$2,832.96",8,0.0,$311.52,903.04,Critical
5,22732,IN-2014-JM156557-41818,6/28/2014,07-01-2014,Second Class,JM-156557,Jim Mitchum,Corporate,NaN,Sydney,...,TEC-PH-5842,Technology,Phones,"Samsung Smart Phone, with Caller ID","$2,862.68",5,0.1,$763.28,897.35,Critical

In [22]:
df1=df[dff]

In [23]:
df1

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
1,26341,IN-2014-JR162107-41675,02-05-2014,02-07-2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,($288.77),923.63,Critical
2,25330,IN-2014-CR127307-41929,10/17/2014,10/18/2014,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,$919.97,915.49,Medium
3,13524,ES-2014-KM1637548-41667,1/28/2014,1/30/2014,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless","$2,892.51",5,0.1,($96.54),910.16,Medium
4,47221,SG-2014-RH9495111-41948,11-05-2014,11-06-2014,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed","$2,832.96",8,0.0,$311.52,903.04,Critical
5,22732,IN-2014-JM156557-41818,6/28/2014,07-01-2014,Second Class,JM-156557,Jim Mitchum,Corporate,NaN,Sydney,...,TEC-PH-5842,Technology,Phones,"Samsung Smart Phone, with Caller ID","$2,862.68",5,0.1,$763.28,897.35,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46629,39399,CA-2013-SB20185140-41416,5/22/2013,5/26/2013,Standard Class,SB-201851404,Sarah Brown,Consumer,90045.0,Los Angeles,...,TEC-MA-6631,Technology,Machines,Zebra GX420t Direct Thermal/Thermal Transfer P...,"$2,973.32",7,0.2,$334.50,510.18,High
48570,46366,CA-2015-SV1081523-42361,12/23/2015,12/25/2015,Second Class,SV-1081523,Stuart Van,Corporate,NaN,Montrï¿½al,...,TEC-PH-5268,Technology,Phones,"Motorola Smart Phone, Full Size","$3,863.88",6,0.0,"$1,159.02",546.56,Critical
48607,31784,CA-2012-SA20830140-41210,10/28/2012,10/30/2012,First Class,SA-208301402,Sue Ann Reed,Consumer,60610.0,Chicago,...,TEC-PH-3138,Technology,Phones,Apple iPhone 5S,"$2,735.95",6,0.2,$341.99,752.51,High
49493,36178,CA-2015-TB21175140-42311,11-03-2015,11-06-2015,Second Class,TB-211751408,Thomas Boland,Corporate,42420.0,Henderson,...,TEC-AC-5098,Technology,Accessories,Logitech diNovo Edge Keyboard,"$2,249.91",9,0.0,$517.48,780.70,Critical
50010,38540,CA-2015-TP21415140-42234,8/18/2015,8/23/2015,Second Class,TP-214151406,Tom Prescott,Consumer,19134.0,Philadelphia,...,FUR-CH-4623,Furniture,Chairs,HON 5400 Series Task Chairs for Big and Tall,"$4,416.17",9,0.3,($630.88),566.65,Medium

In [24]:
df1.shape

(120, 24)

In [25]:
df2=df1["Category"]=="Technology"

In [26]:
df3=df1[df2]

In [27]:
df4=df3['Country']=='India'

In [28]:
df5=df3[df4] #list of Order ID's where the Indian customer's have bought the things under the category 'Technology' after paying the Shipping Cost more than 500

In [29]:
df5['Order ID']

41    IN-2015-BF1100558-42319
48    IN-2015-SW2027558-42125
55    IN-2013-SG2047058-41424
90    IN-2013-GP1474058-41419
Name: Order ID, dtype: object

In [30]:
#list of Order ID's where the Indian customer's have bought the things under the category 'Technology' after paying the Shipping Cost more than 500.
cf=(df['Country']== 'India') & (df['Category']=='Technology')&(df['Shipping Cost']>500)

In [31]:
df6=df[cf]

In [32]:
df6

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
41,29272,IN-2015-BF1100558-42319,11-11-2015,11/15/2015,Standard Class,BF-1100558,Barry Franz,Home Office,NaN,Gorakhpur,...,TEC-PH-5269,Technology,Phones,"Motorola Smart Phone, with Caller ID","$4,518.78",7,0.0,$632.52,658.69,High
48,28701,IN-2015-SW2027558-42125,05-01-2015,05-01-2015,Same Day,SW-2027558,Scott Williamson,Consumer,NaN,Jamshedpur,...,TEC-MA-5007,Technology,Machines,"Konica Inkjet, White","$2,174.13",7,0.0,$500.01,637.86,Critical
55,29047,IN-2013-SG2047058-41424,5/30/2013,5/31/2013,First Class,SG-2047058,Sheri Gordon,Consumer,NaN,Bhopal,...,TEC-CO-4590,Technology,Copiers,"Hewlett Wireless Fax, Color","$1,526.52",4,0.0,$732.72,625.77,Critical
90,29600,IN-2013-GP1474058-41419,5/25/2013,5/28/2013,Second Class,GP-1474058,Guy Phonely,Corporate,NaN,Delhi,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$1,916.73",3,0.0,$498.33,548.40,Critical

In [33]:
df6['Order ID']

41    IN-2015-BF1100558-42319
48    IN-2015-SW2027558-42125
55    IN-2013-SG2047058-41424
90    IN-2013-GP1474058-41419
Name: Order ID, dtype: object

In [34]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,11-11-2014,11/13/2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,$221.98,2,0.0,$62.15,40.770,High
1,26341,IN-2014-JR162107-41675,02-05-2014,02-07-2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,($288.77),923.630,Critical
2,25330,IN-2014-CR127307-41929,10/17/2014,10/18/2014,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,$919.97,915.490,Medium
3,13524,ES-2014-KM1637548-41667,1/28/2014,1/30/2014,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless","$2,892.51",5,0.1,($96.54),910.160,Medium
4,47221,SG-2014-RH9495111-41948,11-05-2014,11-06-2014,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed","$2,832.96",8,0.0,$311.52,903.040,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,6/19/2015,6/19/2015,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,OFF-FA-3072,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",$65.10,5,0.0,$4.50,1.010,Medium
51286,34337,US-2014-ZD21925140-41765,05-06-2014,05-10-2014,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,FUR-FU-4070,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",$16.72,5,0.2,$3.34,1.930,High
51287,31315,CA-2012-ZD21925140-41147,8/26/2012,8/31/2012,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,OFF-AR-5321,Office Supplies,Art,Newell 341,$8.56,2,0.0,$2.48,1.580,High
51288,9596,MX-2013-RB1979518-41322,2/17/2013,2/21/2013,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,OFF-BI-2919,Office Supplies,Binders,"Acco Index Tab, Economy",$13.44,2,0.0,$2.40,1.003,Medium
51289,6147,MX-2013-MC1810093-41416,5/22/2013,5/26/2013,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,OFF-PA-3990,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",$61.38,3,0.0,$1.80,1.002,High

In [35]:
#people from the State 'Karnataka' have bought the things under the category 'Technology'
pk=(df['Country']== 'India') & (df['Category']=='Technology')&(df['State']=='Karnataka')

In [36]:
df[pk]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
408,27724,IN-2015-CY1274558-42300,10/23/2015,10/25/2015,First Class,CY-1274558,Craig Yedwab,Corporate,NaN,Bangalore,...,TEC-CO-4578,Technology,Copiers,"Hewlett Fax Machine, Laser",$959.76,3,0.0,$460.62,317.81,Critical
782,27579,IN-2015-JW1522058-42101,04-07-2015,04-12-2015,Standard Class,JW-1522058,Jane Waco,Corporate,NaN,Mangalore,...,TEC-PH-3807,Technology,Phones,"Cisco Smart Phone, with Caller ID","$3,271.20",5,0.0,"$1,341.15",232.45,High
1957,22906,IN-2014-RA1928558-41863,08-12-2014,8/16/2014,Standard Class,RA-1928558,Ralph Arnett,Consumer,NaN,Mangalore,...,TEC-CO-4791,Technology,Copiers,"HP Wireless Fax, High-Speed","$1,075.23",3,0.0,$344.07,136.45,High
2364,28779,IN-2014-BO1135058-41783,5/24/2014,5/30/2014,Standard Class,BO-1135058,Bill Overfelt,Corporate,NaN,Bangalore,...,TEC-CO-3608,Technology,Copiers,"Brother Wireless Fax, Color","$1,140.75",3,0.0,$0.00,119.46,Medium
3200,22204,IN-2014-CM1238558-41755,4/26/2014,4/28/2014,Second Class,CM-1238558,Christopher Martinez,Consumer,NaN,Bangalore,...,TEC-CO-4769,Technology,Copiers,"HP Fax and Copier, Color",$697.32,4,0.0,$292.80,94.93,High
5030,28814,IN-2015-MK1816058-42330,11/22/2015,11/26/2015,Standard Class,MK-1816058,Mike Kennedy,Consumer,NaN,Mangalore,...,TEC-CO-3609,Technology,Copiers,"Brother Wireless Fax, Digital","$1,892.25",5,0.0,$927.15,66.30,Medium
5132,28511,IN-2012-AH1046558-41059,5/30/2012,5/30/2012,Same Day,AH-1046558,Amy Hunt,Consumer,NaN,Belgaum,...,TEC-AC-5132,Technology,Accessories,"Logitech Numeric Keypad, Programmable",$382.56,8,0.0,$68.64,65.04,Medium
5378,21739,IN-2014-TC2147558-41753,4/24/2014,4/26/2014,Second Class,TC-2147558,Tony Chapman,Home Office,NaN,Bangalore,...,TEC-PH-5266,Technology,Phones,"Motorola Signal Booster, with Caller ID",$286.26,2,0.0,$19.98,62.00,Critical
5572,24372,IN-2015-Co1264058-42326,11/18/2015,11/22/2015,Standard Class,Co-1264058,Corey-Lock,Consumer,NaN,Bangalore,...,TEC-PH-3807,Technology,Phones,"Cisco Smart Phone, with Caller ID",$654.24,1,0.0,$268.23,60.28,Medium
7304,22905,IN-2014-RA1928558-41863,08-12-2014,8/16/2014,Standard Class,RA-1928558,Ralph Arnett,Consumer,NaN,Mangalore,...,TEC-PH-3139,Technology,Phones,"Apple Office Telephone, Cordless",$408.78,6,0.0,$192.06,46.71,High
12782,21980,IN-2013-MA1756058-41275,01-01-2013,01-06-2013,Standard Class,MA-1756058,Matt Abelman,Home Office,NaN,Bellary,...,TEC-AC-5194,Technology,Accessories,"Memorex Flash Drive, Erganomic",$244.89,9,0.0,$65.88,24.56,High
12996,29865,IN-2013-MH1745558-41590,11-12-2013,11/17/2013,Second Class,MH-1745558,Mark Hamilton,Consumer,NaN,Bangalore,...,TEC-AC-5866,Technology,Accessories,"SanDisk Keyboard, Programmable",$414.90,5,0.0,$124.35,24.00,Medium
14278,22904,IN-2014-RA1928558-41863,08-12-2014,8/16/2014,Standard Class,RA-1928558,Ralph Arnett,Consumer,NaN,Mangalore,...,TEC-MA-6139,Technology,Machines,"StarTech Card Printer, Wireless",$163.50,1,0.0,$37.59,21.12,High
16364,23769,IN-2013-TB2152058-41430,06-05-2013,06-10-2013,Standard Class,TB-2152058,Tracy Blumstein,Consumer,NaN,Bangalore,...,TEC-PH-3127,Technology,Phones,"Apple Audio Dock, Cordless",$339.48,2,0.0,$27.12,17.34,Medium
16877,27013,IN-2013-ON1871558-41636,12/28/2013,01-02-2014,Standard Class,ON-1871558,Odella Nelson,Corporate,NaN,Bangalore,...,TEC-MA-5542,Technology,Machines,"Panasonic Card Printer, Durable",$347.88,2,0.0,$163.50,16.53,Medium
17155,24373,IN-2015-Co1264058-42326,11/18/2015,11/22/2015,Standard Class,Co-1264058,Corey-Lock,Consumer,NaN,Bangalore,...,TEC-AC-4152,Technology,Accessories,"Enermax Flash Drive, Erganomic",$196.65,5,0.0,$82.50,16.11,Medium
18314,24367,IN-2015-Co1264058-42326,11/18/2015,11/22/2015,Standard Class,Co-1264058,Corey-Lock,Consumer,NaN,Bangalore,...,TEC-AC-5872,Technology,Accessories,"SanDisk Memory Card, Bluetooth",$224.82,2,0.0,$6.72,14.51,Medium
18733,22205,IN-2014-CM1238558-41755,4/26/2014,4/28/2014,Second Class,CM-1238558,Christopher Martinez,Consumer,NaN,Bangalore,...,TEC-PH-3817,Technology,Phones,"Cisco Speaker Phone, VoIP",$277.14,2,0.0,$38.76,13.96,High
21482,27041,IN-2014-PW1903058-41999,12/26/2014,12/30/2014,Standard Class,PW-1903058,Pauline Webber,Corporate,NaN,Shimoga,...,TEC-AC-5118,Technology,Accessories,"Logitech Keyboard, USB",$145.32,2,0.0,$45.00,11.00,Medium
21675,23579,IN-2014-LC1688558-41940,10/28/2014,10/30/2014,Second Class,LC-1688558,Lena Creighton,Consumer,NaN,Bangalore,...,TEC-AC-3397,Technology,Accessories,"Belkin Numeric Keypad, Erganomic",$177.75,3,0.0,$30.15,10.84,Medium
35956,20727,IN-2013-AT1043558-41607,11/29/2013,12-03-2013,Standard Class,AT-1043558,Alyssa Tate,Home Office,NaN,Bellary,...,TEC-AC-5101,Technology,Accessories,"Logitech Flash Drive, Programmable",$32.01,1,0.0,$10.23,3.30,High

In [37]:
cnpk=df[pk]

In [38]:
cnpk['Customer Name']

408              Craig Yedwab
782                 Jane Waco
1957             Ralph Arnett
2364            Bill Overfelt
3200     Christopher Martinez
5030             Mike Kennedy
5132                 Amy Hunt
5378             Tony Chapman
5572               Corey-Lock
7304             Ralph Arnett
12782            Matt Abelman
12996           Mark Hamilton
14278            Ralph Arnett
16364         Tracy Blumstein
16877           Odella Nelson
17155              Corey-Lock
18314              Corey-Lock
18733    Christopher Martinez
21482          Pauline Webber
21675          Lena Creighton
35956             Alyssa Tate
Name: Customer Name, dtype: object

In [39]:
#list of countries where the 'Profit' and 'Shipping Cost' are greater than or equal to 200 and 300 respectively.

In [40]:
df.shape

(51290, 24)

In [41]:
df['Shipping Cost']>300

0        False
1         True
2         True
3         True
4         True
         ...
51285    False
51286    False
51287    False
51288    False
51289    False
Name: Shipping Cost, Length: 51290, dtype: bool

In [42]:
df[['Profit','Shipping Cost']]

          Profit  Shipping Cost
0        $62.15          40.770
1      ($288.77)        923.630
2       $919.97         915.490
3       ($96.54)        910.160
4       $311.52         903.040
...          ...            ...
51285     $4.50           1.010
51286     $3.34           1.930
51287     $2.48           1.580
51288     $2.40           1.003
51289     $1.80           1.002

[51290 rows x 2 columns]

In [43]:
df['Profit'].dtype

dtype('O')

In [44]:
df.dtypes

Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
Postal Code       float64
City               object
State              object
Country            object
Region             object
Market             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales              object
Quantity            int64
Discount          float64
Profit             object
Shipping Cost     float64
Order Priority     object
dtype: object

In [45]:
# v1=lambda x:float(x[1:-1])
# df.Profit=df.Profit.apply(v1)

In [46]:
x=df['Profit']

In [47]:
x=pd.to_numeric(x.replace('[^10-9\.-]','',regex=True))
x

0         62.15
1        288.77
2        919.97
3         96.54
4        311.52
          ...
51285      4.50
51286      3.34
51287      2.48
51288      2.40
51289      1.80
Name: Profit, Length: 51290, dtype: float64

In [48]:
xf=pd.DataFrame(x)
xf

       Profit
0       62.15
1      288.77
2      919.97
3       96.54
4      311.52
...       ...
51285    4.50
51286    3.34
51287    2.48
51288    2.40
51289    1.80

[51290 rows x 1 columns]

In [49]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,11-11-2014,11/13/2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,$221.98,2,0.0,$62.15,40.770,High
1,26341,IN-2014-JR162107-41675,02-05-2014,02-07-2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,($288.77),923.630,Critical
2,25330,IN-2014-CR127307-41929,10/17/2014,10/18/2014,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,$919.97,915.490,Medium
3,13524,ES-2014-KM1637548-41667,1/28/2014,1/30/2014,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless","$2,892.51",5,0.1,($96.54),910.160,Medium
4,47221,SG-2014-RH9495111-41948,11-05-2014,11-06-2014,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed","$2,832.96",8,0.0,$311.52,903.040,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,6/19/2015,6/19/2015,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,OFF-FA-3072,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",$65.10,5,0.0,$4.50,1.010,Medium
51286,34337,US-2014-ZD21925140-41765,05-06-2014,05-10-2014,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,FUR-FU-4070,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",$16.72,5,0.2,$3.34,1.930,High
51287,31315,CA-2012-ZD21925140-41147,8/26/2012,8/31/2012,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,OFF-AR-5321,Office Supplies,Art,Newell 341,$8.56,2,0.0,$2.48,1.580,High
51288,9596,MX-2013-RB1979518-41322,2/17/2013,2/21/2013,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,OFF-BI-2919,Office Supplies,Binders,"Acco Index Tab, Economy",$13.44,2,0.0,$2.40,1.003,Medium
51289,6147,MX-2013-MC1810093-41416,5/22/2013,5/26/2013,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,OFF-PA-3990,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",$61.38,3,0.0,$1.80,1.002,High

In [50]:
df.update(xf)

In [51]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,11-11-2014,11/13/2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,$221.98,2,0.0,62.15,40.770,High
1,26341,IN-2014-JR162107-41675,02-05-2014,02-07-2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,288.77,923.630,Critical
2,25330,IN-2014-CR127307-41929,10/17/2014,10/18/2014,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,919.97,915.490,Medium
3,13524,ES-2014-KM1637548-41667,1/28/2014,1/30/2014,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless","$2,892.51",5,0.1,96.54,910.160,Medium
4,47221,SG-2014-RH9495111-41948,11-05-2014,11-06-2014,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed","$2,832.96",8,0.0,311.52,903.040,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,6/19/2015,6/19/2015,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,OFF-FA-3072,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",$65.10,5,0.0,4.5,1.010,Medium
51286,34337,US-2014-ZD21925140-41765,05-06-2014,05-10-2014,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,FUR-FU-4070,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",$16.72,5,0.2,3.34,1.930,High
51287,31315,CA-2012-ZD21925140-41147,8/26/2012,8/31/2012,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,OFF-AR-5321,Office Supplies,Art,Newell 341,$8.56,2,0.0,2.48,1.580,High
51288,9596,MX-2013-RB1979518-41322,2/17/2013,2/21/2013,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,OFF-BI-2919,Office Supplies,Binders,"Acco Index Tab, Economy",$13.44,2,0.0,2.4,1.003,Medium
51289,6147,MX-2013-MC1810093-41416,5/22/2013,5/26/2013,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,OFF-PA-3990,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",$61.38,3,0.0,1.8,1.002,High

In [52]:
ps=(df['Profit']>200) & (df['Shipping Cost']>300)

In [53]:
dc=df[ps]

In [54]:
dc

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
1,26341,IN-2014-JR162107-41675,02-05-2014,02-07-2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,288.77,923.63,Critical
2,25330,IN-2014-CR127307-41929,10/17/2014,10/18/2014,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,919.97,915.49,Medium
4,47221,SG-2014-RH9495111-41948,11-05-2014,11-06-2014,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed","$2,832.96",8,0.0,311.52,903.04,Critical
5,22732,IN-2014-JM156557-41818,6/28/2014,07-01-2014,Second Class,JM-156557,Jim Mitchum,Corporate,NaN,Sydney,...,TEC-PH-5842,Technology,Phones,"Samsung Smart Phone, with Caller ID","$2,862.68",5,0.1,763.28,897.35,Critical
6,30570,IN-2012-TS2134092-41219,11-06-2012,11-08-2012,First Class,TS-2134092,Toby Swindell,Consumer,NaN,Porirua,...,FUR-CH-5378,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable","$1,822.08",4,0.0,564.84,894.77,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50010,38540,CA-2015-TP21415140-42234,8/18/2015,8/23/2015,Second Class,TP-214151406,Tom Prescott,Consumer,19134.0,Philadelphia,...,FUR-CH-4623,Furniture,Chairs,HON 5400 Series Task Chairs for Big and Tall,"$4,416.17",9,0.3,630.88,566.65,Medium
50471,39309,CA-2015-TB21625140-42150,5/26/2015,5/26/2015,Same Day,TB-216251406,Trudy Brown,Consumer,10009.0,New York City,...,OFF-BI-4339,Office Supplies,Binders,GBC DocuBind P100 Manual Binding Machine,$663.92,5,0.2,207.48,314.27,Critical
50915,36004,CA-2015-WB21850140-42185,6/30/2015,07-01-2015,First Class,WB-218501404,William Brown,Consumer,90049.0,Los Angeles,...,OFF-BI-4342,Office Supplies,Binders,GBC DocuBind TL200 Manual Binding Machine,$895.92,5,0.2,302.37,337.16,High
51151,34367,CA-2012-YC21895140-41229,11/16/2012,11/21/2012,Standard Class,YC-218951406,Yoseph Carroll,Corporate,19711.0,Newark,...,OFF-ST-6020,Office Supplies,Storage,Smead Adjustable Mobile File Trolley with Lock...,"$2,934.33",7,0.0,792.27,428.80,High
51152,32050,CA-2014-YC21895140-41737,04-08-2014,04-10-2014,First Class,YC-218951404,Yoseph Carroll,Corporate,94110.0,San Francisco,...,TEC-CO-4584,Technology,Copiers,Hewlett Packard 610 Color Digital Copier / Pri...,"$1,199.98",3,0.2,374.99,363.78,High

In [55]:
dc['Country']

1            Australia
2            Australia
4              Senegal
5            Australia
6          New Zealand
             ...
50010    United States
50471    United States
50915    United States
51151    United States
51152    United States
Name: Country, Length: 361, dtype: object

In [56]:
# let's create a dataframe of type object and convert it into a float or integer
cf=pd.DataFrame({ 'profit': ['44$','67$','89$','95$','23$']})
cf

  profit
0    44$
1    67$
2    89$
3    95$
4    23$

In [57]:
cf['profit'].dtypes

dtype('O')

In [58]:
cf['profit']=pd.to_numeric(x.replace('[^10-9\.-]','',regex=True))

In [59]:
cf['profit']

0     62.15
1    288.77
2    919.97
3     96.54
4    311.52
Name: profit, dtype: float64

In [60]:
#list of Indian states where the people have purchased the things under the category Technology.
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,11-11-2014,11/13/2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,$221.98,2,0.0,62.15,40.770,High
1,26341,IN-2014-JR162107-41675,02-05-2014,02-07-2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,288.77,923.630,Critical
2,25330,IN-2014-CR127307-41929,10/17/2014,10/18/2014,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,919.97,915.490,Medium
3,13524,ES-2014-KM1637548-41667,1/28/2014,1/30/2014,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless","$2,892.51",5,0.1,96.54,910.160,Medium
4,47221,SG-2014-RH9495111-41948,11-05-2014,11-06-2014,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed","$2,832.96",8,0.0,311.52,903.040,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,6/19/2015,6/19/2015,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,OFF-FA-3072,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",$65.10,5,0.0,4.5,1.010,Medium
51286,34337,US-2014-ZD21925140-41765,05-06-2014,05-10-2014,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,FUR-FU-4070,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",$16.72,5,0.2,3.34,1.930,High
51287,31315,CA-2012-ZD21925140-41147,8/26/2012,8/31/2012,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,OFF-AR-5321,Office Supplies,Art,Newell 341,$8.56,2,0.0,2.48,1.580,High
51288,9596,MX-2013-RB1979518-41322,2/17/2013,2/21/2013,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,OFF-BI-2919,Office Supplies,Binders,"Acco Index Tab, Economy",$13.44,2,0.0,2.4,1.003,Medium
51289,6147,MX-2013-MC1810093-41416,5/22/2013,5/26/2013,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,OFF-PA-3990,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",$61.38,3,0.0,1.8,1.002,High

In [61]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Postal Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [62]:
ti=(df['Category']=='Technology') & (df['Country']=='India')

In [63]:
c=df[ti]

In [64]:
c['State']

41              Haryana
48            Jharkhand
55       Madhya Pradesh
90                Delhi
130             Gujarat
              ...
39631            Kerala
40262            Punjab
42345             Bihar
43976         Telangana
51172        Tamil Nadu
Name: State, Length: 354, dtype: object

In [65]:
# Find the overall rank of India where the 'Profit' is maximum under the category 'Technology'

In [66]:
ti=(df['Category']=='Technology') & (df['Country']=='India')

In [67]:
df[ti]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
41,29272,IN-2015-BF1100558-42319,11-11-2015,11/15/2015,Standard Class,BF-1100558,Barry Franz,Home Office,NaN,Gorakhpur,...,TEC-PH-5269,Technology,Phones,"Motorola Smart Phone, with Caller ID","$4,518.78",7,0.0,632.52,658.69,High
48,28701,IN-2015-SW2027558-42125,05-01-2015,05-01-2015,Same Day,SW-2027558,Scott Williamson,Consumer,NaN,Jamshedpur,...,TEC-MA-5007,Technology,Machines,"Konica Inkjet, White","$2,174.13",7,0.0,500.01,637.86,Critical
55,29047,IN-2013-SG2047058-41424,5/30/2013,5/31/2013,First Class,SG-2047058,Sheri Gordon,Consumer,NaN,Bhopal,...,TEC-CO-4590,Technology,Copiers,"Hewlett Wireless Fax, Color","$1,526.52",4,0.0,732.72,625.77,Critical
90,29600,IN-2013-GP1474058-41419,5/25/2013,5/28/2013,Second Class,GP-1474058,Guy Phonely,Corporate,NaN,Delhi,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$1,916.73",3,0.0,498.33,548.40,Critical
130,23880,IN-2014-SV2081558-41968,11/25/2014,11/27/2014,First Class,SV-2081558,Stuart Van,Corporate,NaN,Vadodara,...,TEC-CO-4577,Technology,Copiers,"Hewlett Fax Machine, High-Speed","$1,590.60",5,0.0,572.55,493.20,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39631,21504,IN-2013-JR1570058-41441,6/16/2013,6/22/2013,Standard Class,JR-1570058,Jocasta Rupert,Consumer,NaN,Kollam,...,TEC-AC-4178,Technology,Accessories,"Enermax Numeric Keypad, Bluetooth",$114.66,2,0.0,4.56,2.33,Medium
40262,21321,IN-2014-GZ1447058-41721,3/23/2014,3/27/2014,Standard Class,GZ-1447058,Gary Zandusky,Consumer,NaN,Ludhiana,...,TEC-AC-5221,Technology,Accessories,"Memorex Numeric Keypad, Erganomic",$93.42,2,0.0,42.96,2.18,Medium
42345,21930,IN-2015-CR1282058-42294,10/17/2015,10/21/2015,Standard Class,CR-1282058,Cyra Reiten,Home Office,NaN,Patna,...,TEC-PH-5838,Technology,Phones,"Samsung Signal Booster, with Caller ID",$136.59,1,0.0,57.36,1.92,High
43976,26138,IN-2015-LD1700558-42101,04-07-2015,04-11-2015,Standard Class,LD-1700558,Lisa DeCherney,Consumer,NaN,Kukatpalli,...,TEC-CO-3591,Technology,Copiers,"Brother Fax and Copier, Color",$385.86,2,0.0,84.84,1.77,Medium
51172,29523,IN-2014-AS1013558-41817,6/27/2014,07-03-2014,Standard Class,AS-1013558,Adrian Shami,Home Office,NaN,Nagercoil,...,TEC-AC-3388,Technology,Accessories,"Belkin Memory Card, Bluetooth",$114.81,1,0.0,32.13,1.06,Medium

In [68]:
df[ti].rank()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
41,322.0,252.0,163.5,156.0,242.5,46.0,43.0,312.0,NaN,134.0,...,302.0,177.5,295.0,236.0,211.0,320.5,172.0,341.0,354.0,88.0
48,303.0,346.0,30.0,29.5,53.0,326.0,313.0,89.0,NaN,171.5,...,198.5,177.5,211.0,176.5,112.0,320.5,172.0,330.0,353.0,15.5
55,316.0,145.5,271.5,259.0,23.5,314.5,316.5,89.0,NaN,63.5,...,149.5,177.5,144.5,171.5,30.5,217.5,172.0,344.5,352.0,15.5
90,337.0,99.0,265.0,253.0,95.0,150.0,156.0,223.5,NaN,98.0,...,329.5,177.5,295.0,263.5,41.0,153.5,172.0,329.0,351.0,15.5
130,126.0,223.0,186.5,178.0,23.5,322.0,324.0,223.5,NaN,339.0,...,141.0,177.5,144.5,161.0,32.0,268.5,172.0,337.0,350.0,15.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39631,34.0,107.0,280.0,275.0,242.5,188.0,183.0,89.0,NaN,194.5,...,35.5,177.5,51.5,120.5,52.5,76.5,172.0,16.5,5.0,254.5
40262,29.0,181.5,236.5,224.5,242.5,154.5,148.5,89.0,NaN,216.0,...,74.0,177.5,51.5,218.0,341.5,76.5,172.0,106.5,4.0,254.5
42345,48.0,271.0,132.0,126.0,242.5,89.0,97.0,312.0,NaN,268.0,...,347.0,177.5,295.0,300.0,67.0,17.5,172.0,130.0,3.0,88.0
43976,210.0,317.5,25.0,21.5,242.5,220.5,222.5,89.0,NaN,202.5,...,106.0,177.5,144.5,53.0,208.0,76.5,172.0,170.0,2.0,254.5
51172,333.0,160.5,296.5,55.5,242.5,33.0,8.0,312.0,NaN,248.5,...,4.0,177.5,51.5,33.0,54.0,17.5,172.0,88.0,1.0,254.5

In [69]:
# Display the data with min, max, average and std of 'Profit' & 'Sales' for each Sub-Category under each Category"